Login_app/urls.py
from django.urls import re_path as url, path
from Login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user-login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls')),
]

Login_app/models.py
from django.db import models
from django.contrib.auth.models import User


# username, password, email

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserForm, UserInfoForm
from Login_app.models import UserInfo
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.http import *
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def login_page(request):
    dict = {'title':'Login Page'}
    return render(request, 'Login_app/login.html', context=dict)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse("Account is not active!!")
        else:
            return HttpResponse("Login details are wrong!!")
    else:
        return HttpResponseRedirect(reverse('Login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))

def index(request):
    dict = {'title':'Home Page'}

    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        dict.update({'user_basic_info':user_basic_info, 'user_more_info':user_more_info})
    return render(request, 'Login_app/index.html', context=dict)

def register(request):
    # dict = {'title':'Registration Form'}

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user
            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            user_info.save()
            registered = True
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    dict = {'title':'Registration Form', 'user_form':user_form, 'user_info_form':user_info_form, 'registered':registered}
    return render(request, 'Login_app/register.html', context=dict)

templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"   integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"   crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"  integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"  crossorigin="anonymous"></script>
    <title>{{ title }}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_app:index' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_app:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

templates/Login_app/index.html
{% extends 'Login_app/base.html' %}
{% block body_block %}

{% if user.is_authenticated %}
<p>Username: {{ user_basic_info.username }}</p>
<p>Email: {{ user_basic_info.email }}</p>
<p><a href="{{ user_more_info.facebook_id }}" target="_blank" class="text-decoration-none">Facebook ID</a></p>
<img src="/media/{{ user_more_info.profile_pic }}" alt="profile photo" width="100px" height="120px">
{% else %}
<h3 class="alert alert-primary">You are not logged in !!</h3>
{% endif %}

{% endblock %}

templates/Login_app/login.html
{% extends 'Login_app/base.html' %}
{% block body_block %}

<h3>Please Login:</h3>
<form action="{% url 'Login_app:user_login' %}" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username" required><br><br>
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter password" required><br><br>

    {% csrf_token %}
    <input type="submit" name="submit" value="Login">
</form>

{% endblock %}

templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block body_block %}

{% if registered %}
<h4 class="alert alert-success">Congrates! Registration Successfull!!</h4>
{% else %}
<form enctype="multipart/form-data" method="POST">
    {{ user_form.as_p }}
    {{ user_info_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}

{% endblock %}